// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TicketMasterResponse;
//
//    var topLevel = TopLevel.FromJson(jsonString);

namespace TicketMasterResponse
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TopLevel
    {
        [JsonProperty("_embedded")]
        public TopLevelEmbedded Embedded { get; set; }

        [JsonProperty("_links")]
        public TopLevelLinks Links { get; set; }

        [JsonProperty("page")]
        public Page Page { get; set; }
    }

    public partial class TopLevelEmbedded
    {
        [JsonProperty("events")]
        public Event[] Events { get; set; }
    }

    public partial class Event
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("test")]
        public bool Test { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("locale")]
        public long Locale { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("sales")]
        public Sales Sales { get; set; }

        [JsonProperty("dates")]
        public Dates Dates { get; set; }

        [JsonProperty("classifications")]
        public Classification[] Classifications { get; set; }

        [JsonProperty("info", NullValueHandling = NullValueHandling.Ignore)]
        public string Info { get; set; }

        [JsonProperty("priceRanges")]
        public PriceRange[] PriceRanges { get; set; }

        [JsonProperty("ticketLimit", NullValueHandling = NullValueHandling.Ignore)]
        public Accessibility TicketLimit { get; set; }

        [JsonProperty("_links")]
        public EventLinks Links { get; set; }

        [JsonProperty("_embedded")]
        public EventEmbedded Embedded { get; set; }

        [JsonProperty("promoter", NullValueHandling = NullValueHandling.Ignore)]
        public Promoter Promoter { get; set; }

        [JsonProperty("promoters", NullValueHandling = NullValueHandling.Ignore)]
        public Promoter[] Promoters { get; set; }

        [JsonProperty("accessibility", NullValueHandling = NullValueHandling.Ignore)]
        public Accessibility Accessibility { get; set; }

        [JsonProperty("pleaseNote", NullValueHandling = NullValueHandling.Ignore)]
        public string PleaseNote { get; set; }

        [JsonProperty("products", NullValueHandling = NullValueHandling.Ignore)]
        public Product[] Products { get; set; }

        [JsonProperty("seatmap", NullValueHandling = NullValueHandling.Ignore)]
        public Seatmap Seatmap { get; set; }
    }

    public partial class Accessibility
    {
        [JsonProperty("info")]
        public string Info { get; set; }
    }

    public partial class Classification
    {
        [JsonProperty("primary")]
        public bool Primary { get; set; }

        [JsonProperty("segment")]
        public Genre Segment { get; set; }

        [JsonProperty("genre")]
        public Genre Genre { get; set; }

        [JsonProperty("subGenre")]
        public Genre SubGenre { get; set; }

        [JsonProperty("type")]
        public Genre Type { get; set; }

        [JsonProperty("subType")]
        public Genre SubType { get; set; }

        [JsonProperty("family")]
        public bool Family { get; set; }
    }

    public partial class Genre
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Dates
    {
        [JsonProperty("start")]
        public Start Start { get; set; }

        [JsonProperty("timezone")]
        public long Timezone { get; set; }

        [JsonProperty("status")]
        public Status Status { get; set; }

        [JsonProperty("spanMultipleDays")]
        public bool SpanMultipleDays { get; set; }
    }

    public partial class Start
    {
        [JsonProperty("localDate")]
        public DateTimeOffset LocalDate { get; set; }

        [JsonProperty("localTime")]
        public DateTimeOffset LocalTime { get; set; }

        [JsonProperty("dateTime")]
        public DateTimeOffset DateTime { get; set; }

        [JsonProperty("dateTBD")]
        public bool DateTbd { get; set; }

        [JsonProperty("dateTBA")]
        public bool DateTba { get; set; }

        [JsonProperty("timeTBA")]
        public bool TimeTba { get; set; }

        [JsonProperty("noSpecificTime")]
        public bool NoSpecificTime { get; set; }
    }

    public partial class Status
    {
        [JsonProperty("code")]
        public long Code { get; set; }
    }

    public partial class EventEmbedded
    {
        [JsonProperty("venues")]
        public Venue[] Venues { get; set; }

        [JsonProperty("attractions")]
        public Attraction[] Attractions { get; set; }
    }

    public partial class Attraction
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("test")]
        public bool Test { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("locale")]
        public long Locale { get; set; }

        [JsonProperty("externalLinks", NullValueHandling = NullValueHandling.Ignore)]
        public ExternalLinks ExternalLinks { get; set; }

        [JsonProperty("images")]
        public Image[] Images { get; set; }

        [JsonProperty("classifications")]
        public Classification[] Classifications { get; set; }

        [JsonProperty("upcomingEvents")]
        public Dictionary<string, long> UpcomingEvents { get; set; }

        [JsonProperty("_links")]
        public AttractionLinks Links { get; set; }

        [JsonProperty("aliases", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Aliases { get; set; }
    }

    public partial class ExternalLinks
    {
        [JsonProperty("youtube", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Youtube { get; set; }

        [JsonProperty("twitter", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Twitter { get; set; }

        [JsonProperty("lastfm", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Lastfm { get; set; }

        [JsonProperty("facebook", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Facebook { get; set; }

        [JsonProperty("wiki", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Wiki { get; set; }

        [JsonProperty("musicbrainz")]
        public Musicbrainz[] Musicbrainz { get; set; }

        [JsonProperty("homepage", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Homepage { get; set; }

        [JsonProperty("itunes", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Itunes { get; set; }

        [JsonProperty("instagram", NullValueHandling = NullValueHandling.Ignore)]
        public Facebook[] Instagram { get; set; }
    }

    public partial class Facebook
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Musicbrainz
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("ratio")]
        public long Ratio { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("fallback")]
        public bool Fallback { get; set; }

        [JsonProperty("attribution", NullValueHandling = NullValueHandling.Ignore)]
        public string Attribution { get; set; }
    }

    public partial class AttractionLinks
    {
        [JsonProperty("self")]
        public First Self { get; set; }
    }

    public partial class First
    {
        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public partial class Venue
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("test")]
        public bool Test { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("locale")]
        public long Locale { get; set; }

        [JsonProperty("postalCode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PostalCode { get; set; }

        [JsonProperty("timezone")]
        public long Timezone { get; set; }

        [JsonProperty("city")]
        public City City { get; set; }

        [JsonProperty("state")]
        public State State { get; set; }

        [JsonProperty("country")]
        public Country Country { get; set; }

        [JsonProperty("address")]
        public Address Address { get; set; }

        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("markets")]
        public Genre[] Markets { get; set; }

        [JsonProperty("dmas")]
        public Dma[] Dmas { get; set; }

        [JsonProperty("upcomingEvents")]
        public UpcomingEvents UpcomingEvents { get; set; }

        [JsonProperty("_links")]
        public AttractionLinks Links { get; set; }

        [JsonProperty("boxOfficeInfo", NullValueHandling = NullValueHandling.Ignore)]
        public BoxOfficeInfo BoxOfficeInfo { get; set; }

        [JsonProperty("parkingDetail", NullValueHandling = NullValueHandling.Ignore)]
        public string ParkingDetail { get; set; }

        [JsonProperty("accessibleSeatingDetail", NullValueHandling = NullValueHandling.Ignore)]
        public string AccessibleSeatingDetail { get; set; }

        [JsonProperty("generalInfo", NullValueHandling = NullValueHandling.Ignore)]
        public GeneralInfo GeneralInfo { get; set; }

        [JsonProperty("images", NullValueHandling = NullValueHandling.Ignore)]
        public Image[] Images { get; set; }

        [JsonProperty("social", NullValueHandling = NullValueHandling.Ignore)]
        public Social Social { get; set; }

        [JsonProperty("aliases", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Aliases { get; set; }
    }

    public partial class Address
    {
        [JsonProperty("line1")]
        public string Line1 { get; set; }
    }

    public partial class BoxOfficeInfo
    {
        [JsonProperty("phoneNumberDetail")]
        public string PhoneNumberDetail { get; set; }

        [JsonProperty("openHoursDetail")]
        public string OpenHoursDetail { get; set; }

        [JsonProperty("acceptedPaymentDetail", NullValueHandling = NullValueHandling.Ignore)]
        public string AcceptedPaymentDetail { get; set; }

        [JsonProperty("willCallDetail", NullValueHandling = NullValueHandling.Ignore)]
        public string WillCallDetail { get; set; }
    }

    public partial class City
    {
        [JsonProperty("name")]
        public long Name { get; set; }
    }

    public partial class Country
    {
        [JsonProperty("name")]
        public long Name { get; set; }

        [JsonProperty("countryCode")]
        public long CountryCode { get; set; }
    }

    public partial class Dma
    {
        [JsonProperty("id")]
        public long Id { get; set; }
    }

    public partial class GeneralInfo
    {
        [JsonProperty("generalRule")]
        public string GeneralRule { get; set; }

        [JsonProperty("childRule")]
        public string ChildRule { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }
    }

    public partial class Social
    {
        [JsonProperty("twitter")]
        public Twitter Twitter { get; set; }
    }

    public partial class Twitter
    {
        [JsonProperty("handle")]
        public string Handle { get; set; }
    }

    public partial class State
    {
        [JsonProperty("name")]
        public long Name { get; set; }

        [JsonProperty("stateCode")]
        public long StateCode { get; set; }
    }

    public partial class UpcomingEvents
    {
        [JsonProperty("_total")]
        public long Total { get; set; }

        [JsonProperty("ticketmaster")]
        public long Ticketmaster { get; set; }

        [JsonProperty("tmr", NullValueHandling = NullValueHandling.Ignore)]
        public long? Tmr { get; set; }
    }

    public partial class EventLinks
    {
        [JsonProperty("self")]
        public First Self { get; set; }

        [JsonProperty("attractions")]
        public First[] Attractions { get; set; }

        [JsonProperty("venues")]
        public First[] Venues { get; set; }
    }

    public partial class PriceRange
    {
        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("currency")]
        public long Currency { get; set; }

        [JsonProperty("min")]
        public double Min { get; set; }

        [JsonProperty("max")]
        public double Max { get; set; }
    }

    public partial class Product
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Promoter
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("name")]
        public long Name { get; set; }

        [JsonProperty("description")]
        public long Description { get; set; }
    }

    public partial class Sales
    {
        [JsonProperty("public")]
        public Public Public { get; set; }

        [JsonProperty("presales", NullValueHandling = NullValueHandling.Ignore)]
        public Presale[] Presales { get; set; }
    }

    public partial class Presale
    {
        [JsonProperty("startDateTime")]
        public DateTimeOffset StartDateTime { get; set; }

        [JsonProperty("endDateTime")]
        public DateTimeOffset EndDateTime { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public Uri Url { get; set; }
    }

    public partial class Public
    {
        [JsonProperty("startDateTime")]
        public DateTimeOffset StartDateTime { get; set; }

        [JsonProperty("startTBD")]
        public bool StartTbd { get; set; }

        [JsonProperty("endDateTime")]
        public DateTimeOffset EndDateTime { get; set; }
    }

    public partial class Seatmap
    {
        [JsonProperty("staticUrl")]
        public Uri StaticUrl { get; set; }
    }

    public partial class TopLevelLinks
    {
        [JsonProperty("first")]
        public First First { get; set; }

        [JsonProperty("self")]
        public First Self { get; set; }

        [JsonProperty("next")]
        public First Next { get; set; }

        [JsonProperty("last")]
        public First Last { get; set; }
    }

    public partial class Page
    {
        [JsonProperty("size")]
        public long Size { get; set; }

        [JsonProperty("totalElements")]
        public long TotalElements { get; set; }

        [JsonProperty("totalPages")]
        public long TotalPages { get; set; }

        [JsonProperty("number")]
        public long Number { get; set; }
    }

    public partial class TopLevel
    {
        public static TopLevel FromJson(string json) => JsonConvert.DeserializeObject<TopLevel>(json, TicketMasterResponse.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TopLevel self) => JsonConvert.SerializeObject(self, TicketMasterResponse.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
